### ISSUE TITLE
Run with docker compose which do not export mysql, redis(-cluster).

### ISSUE THREAD

**Issue by liudonghua123** [eolinker/apinto-dashboard#27]
### Description

Hi, I read the doc about running with docker-compose, but I noticed that some service like mysql, redis(-cluster) are exported to the host which I believe is not best practise due to port conflicts and also not required.

So, I tried to update my own version of docker-compose. But the following docker-compose.yml do not working.

It failed with the following errors, maybe redis(-cluster) or mysql problems.

```yml
version: '3'
services:
  mysql:
    image: mysql:5.7.34
    # image: mysql
    privileged: true
    restart: always
    container_name: mysql
    hostname: mysql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=apinto
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - apinto
  apinto-gateway:
    image: eolinker/apinto-gateway
    container_name: apinto-gateway
    privileged: true
    restart: always
    networks:
      - apinto
    ports:
      - 8099:8099
      - 9400:9400
      - 9401:9401
    volumes:
      - ./apinto/data:/var/lib/apinto
      - ./apinto/log:/var/log/apinto
  apinto-dashboard:
    image: eolinker/apinto-dashboard
    container_name: apinto-dashboard
    privileged: true
    restart: always
    networks:
      - apinto
    ports:
      - 18088:8080
    depends_on:
      - mysql
      - cluster-redis
    environment:
      - MYSQL_USER_NAME=root
      - MYSQL_PWD=123456
      - MYSQL_IP=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=apinto
      - ERROR_DIR=/apinto-dashboard/work/logs
      - ERROR_FILE_NAME=error.log
      - ERROR_LOG_LEVEL=info
      - ERROR_EXPIRE=7d
      - ERROR_PERIOD=day
      - REDIS_ADDR=cluster-redis:7201,cluster-redis:7202,cluster-redis:7203,cluster-redis:7204,cluster-redis:7205,cluster-redis:7206
      - REDIS_PWD=123456
    volumes:
      - ./apinto-dashboard/work:/apinto-dashboard/work
  cluster-redis:
    container_name: cluster-redis
    image: eolinker/cluster-redis:6.2.7
    hostname: cluster-redis
    privileged: true
    restart: always
    networks:
      - apinto
    ports:
      - 7201
      - 7202
      - 7203
      - 7204
      - 7205
      - 7206
    environment:
      - REDIS_PWD=123456
      - PORT=7201
      - HOST=localhost
    volumes: 
      - ./redis-cluster/data:/usr/local/cluster_redis/data
networks:
  apinto:
    driver: bridge
    ipam:
      driver: default
      # config:
      #   - subnet: 172.100.0.0/24

```

```
[root@localhost apinto_dashboard]# docker compose up 
[+] Running 4/0
 ✔ Container mysql             Running                                                                                                    0.0s 
 ✔ Container cluster-redis     Running                                                                                                    0.0s 
 ✔ Container apinto-gateway    Created                                                                                                    0.0s 
 ✔ Container apinto-dashboard  Created                                                                                                    0.0s 
Attaching to apinto-dashboard, apinto-gateway, cluster-redis, mysql
apinto-dashboard  | mysql:
apinto-dashboard  |   user_name: root
apinto-dashboard  |   password: 123456
apinto-dashboard  |   ip: mysql
apinto-dashboard  |   port: 3306
apinto-dashboard  |   db: apinto
apinto-dashboard  | redis:
apinto-dashboard  |   user_name: 
apinto-dashboard  |   password: 123456
apinto-dashboard  |   addr: 
apinto-dashboard  |     - cluster-redis:7201
apinto-dashboard  |     - cluster-redis:7202
apinto-dashboard  |     - cluster-redis:7203
apinto-dashboard  |     - cluster-redis:7204
apinto-dashboard  |     - cluster-redis:7205
apinto-dashboard  |     - cluster-redis:7206
apinto-dashboard  | port: 8080
apinto-dashboard  | error_log:
apinto-dashboard  |   dir: /apinto-dashboard/work/logs
apinto-dashboard  |   file_name: error.log
apinto-dashboard  |   log_level: info
apinto-dashboard  |   log_expire: 7d
apinto-dashboard  |   log_period: day
apinto-dashboard  | 
apinto-dashboard  | 2023/12/01 00:27:27 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 Error 1062: Duplicate entry '1' for key 'PRIMARY'
apinto-dashboard  | [1.612ms] [rows:0] INSERT INTO `namespace` (`name`,`create_time`,`id`) VALUES ('default','2023-12-01 00:27:27.179',1)
apinto-dashboard  | [2023-12-01 00:27:27] [ERRO] get module config version:CLUSTERDOWN Hash slot not served
apinto-dashboard  | [2023-12-01 00:27:27] [WARN] lockKey=updateExtender_1701361647 error=CLUSTERDOWN Hash slot not served
apinto-gateway exited with code 0
apinto-gateway exited with code 0
apinto-gateway exited with code 0
apinto-gateway exited with code 0
apinto-gateway exited with code 0
apinto-gateway exited with code 0
apinto-dashboard  | [2023-12-01 00:27:37] [ERRO] get module config version:dial tcp :7201: connect: connection refused
apinto-gateway exited with code 0
apinto-gateway exited with code 0
apinto-dashboard  | [2023-12-01 00:27:47] [ERRO] get module config version:CLUSTERDOWN Hash slot not served
apinto-dashboard  | [2023-12-01 00:27:57] [ERRO] get module config version:CLUSTERDOWN Hash slot not served
apinto-gateway exited with code 0
apinto-dashboard  | [2023-12-01 00:28:00] [WARN] lockKey=updateExtender_1701361680 error=CLUSTERDOWN The cluster is down
apinto-dashboard  | [2023-12-01 00:28:07] [ERRO] get module config version:CLUSTERDOWN The cluster is down
apinto-dashboard  | [2023-12-01 00:28:17] [ERRO] get module config version:dial tcp :7201: connect: connection refused
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Running 4/4
 ✔ Container apinto-dashboard  Stopped                                                                                                   10.3s 
 ✔ Container apinto-gateway    Stopped                                                                                                    0.0s 
 ✔ Container cluster-redis     Stopped                                                                                                   10.7s 
 ✔ Container mysql             Stopped                                                                                                    1.4s 
canceled
[root@localhost apinto_dashboard]#
```

I do not familar with redis-cluster, could I replace the cluster version to normal redis service and how to do it?

**Comment by liudonghua123** [comment]
I encountered `` record not found [rows:0] SELECT * FROM `module_plugin_enable` WHERE name = 'ext-app' and is_enable = 2 LIMIT 1` `` problems when starting `apinto-dashboard`, but I find the data is exists acturally.

```
[root@localhost apinto_dashboard]# docker compose exec mysql mysql
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
[root@localhost apinto_dashboard]# docker compose exec mysql mysql -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5
Server version: 5.7.34 MySQL Community Server (GPL)

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SELECT * FROM `module_plugin_enable` WHERE name = 'email' and is_enable = 2 LIMIT 1
    -> ;
ERROR 1046 (3D000): No database selected
mysql> use apinto;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> SELECT * FROM `module_plugin_enable` WHERE name = 'email' and is_enable = 2 LIMIT 1;
+----+-------+-------------------+-----------+--------------+------------------------------------------------------+----------+---------------------+
| id | name  | navigation        | is_enable | frontend     | config                                               | operator | update_time         |
+----+-------+-------------------+-----------+--------------+------------------------------------------------------+----------+---------------------+
|  7 | email | navigation.system |         2 | system/email | {"server":"","header":[],"query":[],"initialize":[]} |        0 | 2023-12-06 11:36:38 |
+----+-------+-------------------+-----------+--------------+------------------------------------------------------+----------+---------------------+
1 row in set (0.00 sec)

mysql> exit
Bye
[root@localhost apinto_dashboard]# docker compose run -it --rm apinto-dashboard 
[+] Running 2/0
 ✔ Container mysql          Running                                                                                                                                                                                                    0.0s 
 ✔ Container cluster-redis  Running                                                                                                                                                                                                    0.0s 
mysql:
  user_name: root
  password: 123456
  ip: mysql
  port: 3306
  db: apinto
redis:
  user_name: 
  password: 123456
  addr: 
    - cluster-redis:7201
    - cluster-redis:7202
    - cluster-redis:7203
    - cluster-redis:7204
    - cluster-redis:7205
    - cluster-redis:7206
port: 8080
error_log:
  dir: /apinto-dashboard/work/logs
  file_name: error.log
  log_level: info
  log_expire: 7d
  log_period: day

2023/12/06 12:21:01 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 Error 1062: Duplicate entry '1' for key 'PRIMARY'
[0.891ms] [rows:0] INSERT INTO `namespace` (`name`,`create_time`,`id`) VALUES ('default','2023-12-06 12:21:01.811',1)

2023/12/06 12:21:02 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 record not found
[0.634ms] [rows:0] SELECT * FROM `module_plugin_enable` WHERE name = 'ext-app' and is_enable = 2 LIMIT 1
[2023-12-06 12:21:02] [ERRO] set module config version:CLUSTERDOWN Hash slot not served

2023/12/06 12:21:02 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 record not found
[0.643ms] [rows:0] SELECT * FROM `module_plugin_enable` WHERE name = 'log' and is_enable = 2 LIMIT 1
[2023-12-06 12:21:02] [ERRO] set module config version:CLUSTERDOWN Hash slot not served

2023/12/06 12:21:02 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 record not found
[0.640ms] [rows:0] SELECT * FROM `module_plugin_enable` WHERE name = 'module-plugin' and is_enable = 2 LIMIT 1
[2023-12-06 12:21:02] [ERRO] set module config version:CLUSTERDOWN Hash slot not served

2023/12/06 12:21:02 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 record not found
[0.556ms] [rows:0] SELECT * FROM `module_plugin_enable` WHERE name = 'open_api' and is_enable = 2 LIMIT 1
[2023-12-06 12:21:03] [ERRO] set module config version:CLUSTERDOWN Hash slot not served

2023/12/06 12:21:03 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 record not found
[0.570ms] [rows:0] SELECT * FROM `module_plugin_enable` WHERE name = 'plugin' and is_enable = 2 LIMIT 1
[2023-12-06 12:21:03] [ERRO] set module config version:CLUSTERDOWN Hash slot not served

2023/12/06 12:21:03 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 record not found
[0.771ms] [rows:0] SELECT * FROM `module_plugin_enable` WHERE name = 'plugin-template' and is_enable = 2 LIMIT 1
[2023-12-06 12:21:03] [ERRO] set module config version:CLUSTERDOWN Hash slot not served

2023/12/06 12:21:03 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 record not found
[0.569ms] [rows:0] SELECT * FROM `module_plugin_enable` WHERE name = 'cache' and is_enable = 2 LIMIT 1
[2023-12-06 12:21:03] [ERRO] set module config version:CLUSTERDOWN Hash slot not served

2023/12/06 12:21:04 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 record not found
[0.692ms] [rows:0] SELECT * FROM `module_plugin_enable` WHERE name = 'fuse' and is_enable = 2 LIMIT 1
[2023-12-06 12:21:04] [ERRO] set module config version:CLUSTERDOWN Hash slot not served

2023/12/06 12:21:04 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 record not found
[0.648ms] [rows:0] SELECT * FROM `module_plugin_enable` WHERE name = 'grey' and is_enable = 2 LIMIT 1
[2023-12-06 12:21:04] [ERRO] set module config version:CLUSTERDOWN Hash slot not served
^C
[root@localhost apinto_dashboard]# 
```

**Comment by Dot-Liu** [comment]
The problem here is caused by Redis, which failed to establish the cluster. It may be due to an issue with the Host set by Redis.
![image](https://github.com/eolinker/apinto-dashboard/assets/14105999/480139b1-7f53-422b-b20f-c3c3760fad7e)

The local area network IP of the host should be filled in here.
![image](https://github.com/eolinker/apinto-dashboard/assets/14105999/0241c7f4-c0b2-43f7-bd56-b2265562391b)

After you complete the modifications, follow the steps below to proceed

1. Delete Redis mounting directory
```
rm - rf/ Redis cluster/data
```
2. Restart the Docker container
```
docker Compose Down

docker compose up - d
```

**Comment by liudonghua123** [comment]
@Dot-Liu Thanks, I also noticed that error `CLUSTERDOWN Hash slot not served` is related to cluster of redis, see also https://cloud.tencent.com/developer/article/1919678. And I tested with `HOST=localhost` and `HOST=cluster-redis`, neither of them worked. 

I have to hard-coded the actual IP of `HOST`, But the IP of `cluster-redis` is allocated when the container started. This is a circular loop problem.

And I also have to manually fix the redis cluster problems via use `cluster meet 192.168.32.3 720x` and `redis-cli --pass 123456 --cluster fix 192.168.32.3:7201`.

If the HOST accepts hostname, then it would work for `HOST=cluster-redis`.

```yaml
  cluster-redis:
    container_name: cluster-redis
    image: eolinker/cluster-redis:6.2.7
    hostname: cluster-redis
    privileged: true
    restart: always
    networks:
      - apinto
    ports:
      - 7201
      - 7202
      - 7203
      - 7204
      - 7205
      - 7206
    environment:
      - REDIS_PWD=123456
      - PORT=7201
      # - HOST=localhost
      # - HOST=cluster-redis
      - HOST=192.168.32.3
    volumes: 
      - ./redis-cluster/data:/usr/local/cluster_redis/data
```

```
[root@localhost apinto_dashboard]# # update HOST=192.168.32.3 in compose.yml
[root@localhost apinto_dashboard]# docker compose logs -f
...... 
apinto-dashboard  | [2023-12-06 15:42:00] [WARN] lockKey=updateExtender_1701848520 error=dial tcp :7201: connect: connection refused
apinto-dashboard  | [2023-12-06 15:42:02] [ERRO] get module config version:dial tcp :7201: connect: connection refused
apinto-dashboard  | [2023-12-06 15:42:12] [ERRO] get module config version:dial tcp :7201: connect: connection refused
apinto-dashboard  | [2023-12-06 15:42:22] [ERRO] get module config version:dial tcp :7201: connect: connection refused
apinto-dashboard  | [2023-12-06 15:42:32] [ERRO] get module config version:CLUSTERDOWN Hash slot not served
apinto-dashboard  | [2023-12-06 15:42:42] [ERRO] get module config version:CLUSTERDOWN Hash slot not served
apinto-dashboard  | mysql:
apinto-dashboard  |   user_name: root
apinto-dashboard  |   password: 123456
apinto-dashboard  |   addr: 
apinto-dashboard  |     - cluster-redis:7201
apinto-dashboard  |     - cluster-redis:7202
apinto-dashboard  |     - cluster-redis:7203
apinto-dashboard  |     - cluster-redis:7204
apinto-dashboard  |     - cluster-redis:7205
apinto-dashboard  |     - cluster-redis:7206
apinto-dashboard  | port: 8080
apinto-dashboard  | error_log:
apinto-dashboard  |   dir: /apinto-dashboard/work/logs
apinto-dashboard  |   file_name: error.log
apinto-dashboard  |   log_level: info
apinto-dashboard  |   log_expire: 7d
apinto-dashboard  |   log_period: day
apinto-dashboard  | 
apinto-dashboard  | 2023/12/06 15:42:52 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1/callbacks.go:134 Error 1062: Duplicate entry '1' for key 'PRIMARY'
apinto-dashboard  | [1.024ms] [rows:0] INSERT INTO `namespace` (`name`,`create_time`,`id`) VALUES ('default','2023-12-06 15:42:52.51',1)
apinto-dashboard  | [2023-12-06 15:42:53] [ERRO] get module config version:CLUSTERDOWN Hash slot not served
apinto-dashboard  | [2023-12-06 15:42:53] [WARN] lockKey=updateExtender_1701848573 error=CLUSTERDOWN The cluster is down
apinto-dashboard  | [2023-12-06 15:43:00] [WARN] lockKey=updateExtender_1701848580 error=CLUSTERDOWN The cluster is down
apinto-dashboard  | [2023-12-06 15:43:03] [ERRO] get module config version:dial tcp :7201: connect: connection refused
apinto-dashboard  | [2023-12-06 15:43:13] [ERRO] get module config version:CLUSTERDOWN Hash slot not served
apinto-dashboard  | [2023-12-06 15:43:22] [ERRO] get module config version:CLUSTERDOWN Hash slot not served
^Ccanceled
[root@localhost apinto_dashboard]# docker compose exec cluster-redis bash
root@cluster-redis:/usr/local/cluster_redis# redis-cli -p 7201 --pass 123456
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:7201> cluster info
cluster_state:fail
cluster_slots_assigned:5461
cluster_slots_ok:5461
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:1
cluster_size:1
cluster_current_epoch:1
cluster_my_epoch:1
cluster_stats_messages_sent:0
cluster_stats_messages_received:0
127.0.0.1:7201> cluster nodes
384bb4c7b27be5220e980e9b61ee1d75aed418bd :7201@17201 myself,master - 0 0 1 connected 0-5460
127.0.0.1:7201> cluster meet 192.168.32.3 7202
OK
127.0.0.1:7201> cluster meet 192.168.32.3 7203
OK
127.0.0.1:7201> cluster meet 192.168.32.3 7204
OK
127.0.0.1:7201> cluster meet 192.168.32.3 7205
OK
127.0.0.1:7201> cluster meet 192.168.32.3 7206
OK
127.0.0.1:7201> cluster nodes
384bb4c7b27be5220e980e9b61ee1d75aed418bd 192.168.32.3:7201@17201 myself,master - 0 1701848690000 1 connected 0-5460
178476419653061454ca8815c00ae7cdf574002b 192.168.32.3:7206@17206 master - 0 1701848691356 6 connected
0b4b3523ca3b650421a33df8c6f260712303513f 192.168.32.3:7202@17202 master - 0 1701848691356 2 connected 5461-10922
4958b4669968a4d2f982f4161fdc18fee4aa87e5 192.168.32.3:7205@17205 master - 0 1701848691054 5 connected
add4c8260772281a31941dae3f9da56fdb1c0118 192.168.32.3:7203@17203 master - 0 1701848691356 3 connected 10923-16383
36ac51c5229d974b6de31644c1cce612d5ac8871 192.168.32.3:7204@17204 master - 0 1701848691255 4 connected
127.0.0.1:7201> cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:6
cluster_my_epoch:1
cluster_stats_messages_ping_sent:80
cluster_stats_messages_pong_sent:85
cluster_stats_messages_meet_sent:6
cluster_stats_messages_sent:171
cluster_stats_messages_ping_received:85
cluster_stats_messages_pong_received:86
cluster_stats_messages_received:171
127.0.0.1:7201> set test test
(error) MOVED 6918 192.168.32.3:7202
127.0.0.1:7201> exit
root@cluster-redis:/usr/local/cluster_redis# exit
exit
[root@localhost apinto_dashboard]# 
[root@localhost apinto_dashboard]# docker compose restart apinto-dashboard
[root@localhost apinto_dashboard]# docker compose logs -f # The CLUSTERDOWN Hash slot not served error disappeared now!

```

**Comment by liudonghua123** [comment]
I am new to apinto, and from docs https://help.eolink.com/tutorial/Apinto/c-1406, it seems `eolinker/apinto-gateway` is not necessary for the apinto-dashboard, does it means `eolinker/apinto-dashboard` is included `eolinker/apinto-gateway` already?

**Comment by Dot-Liu** [comment]
The apinto-gateway needs to be deployed separately. We suggest deploying it on two servers to avoid resource contention and performance degradation.

**Comment by Dot-Liu** [comment]
This requires the Redis version to be 7. x, and we have not conducted compatibility testing on the 7. x version of Redis yet, so it should not work now.

**Comment by liudonghua123** [comment]
@Dot-Liu Hi, I build a `redis-cluster` image which support hostname as `cluster-announce-ip` configuration. But when I tried to integrated with apinto-dashboard, I got `"ClusterClient.Ping().Result() error: got 4 elements in cluster info address, expected 2 or 3"`, see https://github.com/redis/go-redis/issues/2085.

Could you update the `go-redis`?

**Comment by Dot-Liu** [comment]
I have reviewed the issue you mentioned and it is indeed a good suggestion, but we need to take some time to verify and avoid compatibility issues with old users due to upgrades. This will take some time, and we will schedule a replacement. Thank you for your suggestion.

**Comment by Dot-Liu** [comment]
Okay, we will process and verify it within this week. If there are no issues, we will deploy the tutorial together this week.

**Comment by Dot-Liu** [comment]
The issue has been resolved, please update to version [v3.3.3](https://github.com/eolinker/apinto-dashboard/releases/tag/v3.3.3)
The tutorial is also updated synchronously. For details, please refer to: https://help.eolink.com/tutorial/Apinto/c-1406#tip2
@liudonghua123

**Comment by liudonghua123** [comment]
@Dot-Liu Thanks, I tried the following [`docker-compose.yml`](https://help.eolink.com/tutorial/Apinto/c-1406#tip2) and [`config.yml`](https://help.eolink.com/tutorial/Apinto/c-1378#tip5). And it seems ok, except sometimes the apinto-dashboard logged out unexpected and I have to re-login. I need to do more deep analysis.

`docker-compose.yml`: 
```yml
version: '3'
services:
  apinto-gateway:
    image: eolinker/apinto-gateway:latest
    tty: true
    privileged: true
    restart: unless-stopped
    ports:
      - 8099:8099
      - 9400:9400
      - 9401:9401
    volumes:
      - ./data:/var/lib/apinto
      - ./log:/var/log/apinto
      - ./config.yml:/etc/apinto/config.yml
  apinto-dashboard:
    image: eolinker/apinto-dashboard:latest
    privileged: true
    restart: unless-stopped
    ports:
      - "38080:8080"
    depends_on:
      - mysql
      - redis_cluster
    environment:
      - MYSQL_USER_NAME=root
      - MYSQL_PWD=123456
      - MYSQL_IP=apinto_mysql
      - MYSQL_PORT=3306
      - MYSQL_DB="apinto"
      - ERROR_DIR=/apinto-dashboard/work/logs
      - ERROR_FILE_NAME=error.log
      - ERROR_LOG_LEVEL=info
      - ERROR_EXPIRE=7d
      - ERROR_PERIOD=day
      - REDIS_ADDR=redis_cluster:7201,redis_cluster:7202,redis_cluster:7203,redis_cluster:7204,redis_cluster:7205,redis_cluster:7206
      - REDIS_PWD=123456
    volumes:
      - ./work:/apinto-dashboard/work
  mysql:
    image: mysql:5.7.34
    privileged: true
    restart: unless-stopped
    container_name: apinto_mysql
    hostname: apinto_mysql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=apinto
    volumes:
      - ./mysql:/var/lib/mysql
  redis_cluster:
    image: eolinker/cluster-redis:7.2.4
    hostname: redis_cluster
    privileged: true
    restart: unless-stopped
    container_name: redis_cluster
    ports:
      - 7201-7206
      - 17201-17206
    environment:
      - REDIS_PWD=123456
      - PORT=7201
      - HOST=redis_cluster
    volumes: 
      - ./redis:/usr/local/cluster_redis/data
```

`config.yml`
```yml
version: 2

client:
  advertise_urls: 
    - http://apinto-gateway:9400
  listen_urls: 
    - http://0.0.0.0:9400
gateway:
  advertise_urls: 
    - http://apinto-gateway:8099
  listen_urls: 
    - http://0.0.0.0:8099
peer: 
  listen_urls: 
    - http://0.0.0.0:9401
  advertise_urls: 
    - http://apinto-gateway:9401
```

**Comment by liudonghua123** [comment]
> @Dot-Liu Thanks, I tried the following [`docker-compose.yml`](https://help.eolink.com/tutorial/Apinto/c-1406#tip2) and [`config.yml`](https://help.eolink.com/tutorial/Apinto/c-1378#tip5). And it seems ok, except sometimes the apinto-dashboard logged out unexpected and I have to re-login. I need to do more deep analysis.
> 
> `docker-compose.yml`:
> 
> ```yaml
> version: '3'
> services:
>   apinto-gateway:
>     image: eolinker/apinto-gateway:latest
>     tty: true
>     privileged: true
>     restart: unless-stopped
>     ports:
>       - 8099:8099
>       - 9400:9400
>       - 9401:9401
>     volumes:
>       - ./data:/var/lib/apinto
>       - ./log:/var/log/apinto
>       - ./config.yml:/etc/apinto/config.yml
>   apinto-dashboard:
>     image: eolinker/apinto-dashboard:latest
>     privileged: true
>     restart: unless-stopped
>     ports:
>       - "38080:8080"
>     depends_on:
>       - mysql
>       - redis_cluster
>     environment:
>       - MYSQL_USER_NAME=root
>       - MYSQL_PWD=123456
>       - MYSQL_IP=apinto_mysql
>       - MYSQL_PORT=3306
>       - MYSQL_DB="apinto"
>       - ERROR_DIR=/apinto-dashboard/work/logs
>       - ERROR_FILE_NAME=error.log
>       - ERROR_LOG_LEVEL=info
>       - ERROR_EXPIRE=7d
>       - ERROR_PERIOD=day
>       - REDIS_ADDR=redis_cluster:7201,redis_cluster:7202,redis_cluster:7203,redis_cluster:7204,redis_cluster:7205,redis_cluster:7206
>       - REDIS_PWD=123456
>     volumes:
>       - ./work:/apinto-dashboard/work
>   mysql:
>     image: mysql:5.7.34
>     privileged: true
>     restart: unless-stopped
>     container_name: apinto_mysql
>     hostname: apinto_mysql
>     command:
>       - "--character-set-server=utf8mb4"
>       - "--collation-server=utf8mb4_unicode_ci"
>     ports:
>       - "3306"
>     environment:
>       - MYSQL_ROOT_PASSWORD=123456
>       - MYSQL_DATABASE=apinto
>     volumes:
>       - ./mysql:/var/lib/mysql
>   redis_cluster:
>     image: eolinker/cluster-redis:7.2.4
>     hostname: redis_cluster
>     privileged: true
>     restart: unless-stopped
>     container_name: redis_cluster
>     ports:
>       - 7201-7206
>       - 17201-17206
>     environment:
>       - REDIS_PWD=123456
>       - PORT=7201
>       - HOST=redis_cluster
>     volumes: 
>       - ./redis:/usr/local/cluster_redis/data
> ```
> 
> `config.yml`
> 
> ```yaml
> version: 2
> 
> client:
>   advertise_urls: 
>     - http://apinto-gateway:9400
>   listen_urls: 
>     - http://0.0.0.0:9400
> gateway:
>   advertise_urls: 
>     - http://apinto-gateway:8099
>   listen_urls: 
>     - http://0.0.0.0:8099
> peer: 
>   listen_urls: 
>     - http://0.0.0.0:9401
>   advertise_urls: 
>     - http://apinto-gateway:9401
> ```

I found the `privileged: true` is not needed for all the services and `tty: true` is required for `eolinker/apinto-gateway` due to the cmd of the image is `CMD ["/bin/sh" "-c" "sh start.sh"]` which is different to `CMD ["/bin/sh" "-c" "./docker_run.sh"]` of `eolinker/apinto-dashboard`.

If I changed the cmd using `entrypoint: ["/bin/sh", "-c", "./start.sh"]`, then `tty: true` is not needed.

Use the default cmd/entrypoint without `tty: true` will failed to start apinto-gateway.

```
[root@localhost apinto]# docker compose up apinto-gateway
[+] Running 2/1
 ✔ Network apinto_default             Created                                                                                                                                                                                          0.4s 
 ✔ Container apinto-apinto-gateway-1  Created                                                                                                                                                                                          0.1s 
Attaching to apinto-gateway-1
apinto-gateway-1 exited with code 0
[root@localhost apinto]#
```

Then the final docker-compose.yml file I used is the following.

<details><summary>docker-compose.yml</summary>

```yml
version: '3'
services:
  apinto-gateway:
    image: eolinker/apinto-gateway:latest
    # tty: true
    restart: unless-stopped
    ports:
      - 8099:8099
      - 9400:9400
      - 9401:9401
    volumes:
      - ./data:/var/lib/apinto
      - ./log:/var/log/apinto
      - ./config.yml:/etc/apinto/config.yml
    entrypoint: ["/bin/sh", "-c", "./start.sh"]
  apinto-dashboard:
    image: eolinker/apinto-dashboard:latest
    restart: unless-stopped
    ports:
      - "38080:8080"
    depends_on:
      - mysql
      - redis_cluster
    environment:
      - MYSQL_USER_NAME=root
      - MYSQL_PWD=123456
      - MYSQL_IP=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB="apinto"
      - ERROR_DIR=/apinto-dashboard/work/logs
      - ERROR_FILE_NAME=error.log
      - ERROR_LOG_LEVEL=info
      - ERROR_EXPIRE=7d
      - ERROR_PERIOD=day
      - REDIS_ADDR=redis_cluster:7201,redis_cluster:7202,redis_cluster:7203,redis_cluster:7204,redis_cluster:7205,redis_cluster:7206
      - REDIS_PWD=123456
    volumes:
      - ./work:/apinto-dashboard/work
  mysql:
    image: mysql:5.7.34
    restart: unless-stopped
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=apinto
    volumes:
      - ./mysql:/var/lib/mysql
  redis_cluster:
    image: eolinker/cluster-redis:7.2.4
    restart: unless-stopped
    ports:
      - 7201-7206
      - 17201-17206
    environment:
      - REDIS_PWD=123456
      - PORT=7201
      - HOST=redis_cluster
    volumes: 
      - ./redis:/usr/local/cluster_redis/data
```

</details>
